# Generated by Django 5.2.9 on 2025-12-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_is_blocked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_block_user", "Может блокировать пользователей"),
                    ("can_view_users", "Может просмамтривать пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
