# Generated by Django 5.2.8 on 2025-11-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Адрес электронной почты подписчика.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Полное имя получателя (Ф.И.О.).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительный комментарий о получателе.",
                        null=True,
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, help_text="Дата добавления получателя."),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["date_added"],
            },
        ),
    ]
