# Generated by Django 5.2.8 on 2025-11-24 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Укажите дату и время первой отправки рассылки.",
                        verbose_name="Дата и время начала рассылки",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Укажите дату и время, после которой рассылка не будет отправляться.",
                        verbose_name="Дата и время окончания рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("running", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        help_text="Текущий статус рассылки (Создана, Запущена, Завершена).",
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Выберите сообщение, которое будет отправлено в этой рассылке.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailings",
                        to="mailings.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        help_text="Выберите получателей для этой рассылки.",
                        related_name="mailings",
                        to="mailings.recipient",
                        verbose_name="Получатели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-start_time"],
            },
        ),
    ]
