# Generated by Django 5.2.8 on 2025-11-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_mailingattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(
                help_text="Адрес электронной почты получателя.",
                max_length=254,
                unique=True,
            ),
        ),
    ]
