# Generated by Django 5.2.8 on 2025-12-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_alter_recipient_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                help_text="Укажите дату и время первой отправки рассылки.",
                verbose_name="Дата и время c какого момента рассылка может быть запущена",
            ),
        ),
    ]
