# Generated by Django 5.2.9 on 2025-12-05 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_alter_mailing_start_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-start_time"],
                "permissions": [
                    ("view_all_mailing", "Может просматривать все рассылки (менеджер)"),
                    ("disable_mailing", "Может отключать рассылки (менеджер)"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["subject"],
                "permissions": [("view_all_message", "Может просматривать все сообщения (менеджер)")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["date_added"],
                "permissions": [
                    (
                        "view_all_recipient",
                        "Может просматривать всех получателей (менеджер)",
                    )
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите создателя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Recipient",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
