# Generated by Django 5.2.9 on 2025-12-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0010_alter_mailing_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-start_time"],
                "permissions": [("disable_mailing", "Может отключать рассылки (менеджер)")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
