# Generated by Django 5.2.9 on 2025-12-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0011_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-start_time"],
                "permissions": [
                    ("disable_mailing", "Может отключать рассылки (менеджер)"),
                    (
                        "view_all_mailing",
                        "Может просматривать рассылки всех пользователей",
                    ),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-timestamp"],
                "permissions": [
                    (
                        "view_all_mailing_attempt",
                        "Может просматривать попытки рассылки всех пользователей",
                    )
                ],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
    ]
