# Generated by Django 5.2.9 on 2025-12-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0012_alter_mailing_options_alter_mailingattempt_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="in_active_status",
            field=models.CharField(
                choices=[("active", "Активна"), ("inactive", "Неактивна")],
                default="active",
                max_length=20,
            ),
        ),
    ]
